pykern/pksetup.py
In order to test a module that contains C/C++ code, it might be necessary to tweak the compilation parameters according to the environment where tox is running. Currently it does not pass compilation flags like `CFLAGS` and the like.
A way to override this manually is:
```
> export TOX_TESTENV_PASSENV='CFLAGS CPPFLAGS LDFLAGS'
> python setup.py tox
```
But I am afraid this hidden and requires people to search for the information. I think we should do the right thing and do not tamper with those environment variables if they have been set for a reason.
=> Pass compiler flags down to the Tox test environment

pykern/pkcli/projex.py, pykern/pkcollections.py, pykern/pkunit.py, tests/pkcollections_test.py
unused: map_keys, map_values, map_to_dict, mapping_merge, map_items
Hide object_pairs_hook since wasn't used outside
[wait to release this until after prod release of sirepo]
Depends on https://github.com/radiasoft/sirepo/pull/2758
=> Fix #77 removed OrderedMapping, and mapping_merge, map_* functions

setup.py
In tox 3.21.0 the high constraint for importlib-metadata was relaxed.
https://github.com/tox-dev/tox/pull/1764
A matching PR was also merged in virtualenv.
https://github.com/pypa/virtualenv/pull/2020
So, we no longer need to have a high constraint which should solve the
conflict (importlib-metadata 4.3.0 was installed but we expected <2).
=> Fix #99: Relax high constraint for importlib-metadata

pykern/pkio.py, pykern/pkresource.py
Sirepo needs to be able to load resources that live outside of its namespace.
This updates pkresource to support searching for resources beyond the
caller_context / caller_module.
The additional packages are searched first so resources found in them can
override the resources in Sirepo (or any caller context/module).
=> Fix radiasoft/sirepo#3732: Update pkresource to search additional packages

pykern/pkio.py, tests/pkio_test.py
- Reduced number of local variables
- Hoisted loop invariants
- Simplified no file_re case
- Removed unnecessary comment which can't be enforced
=> fix #125 walk_tree simplified

pykern/pkunit.py, tests/pkunit1_data/a.in/res.json, tests/pkunit1_data/a.out/res.json
- `tests/pkunit1_data/a.{in,out}/res.json`
- also ran sirepo tests that use file_eq
- no
- none
- yes
- no, because was a failing case
=> Fix #151 actual_path json exists just file compare

pykern/pkcli/test.py, pykern/pksetup.py, setup.py
* _assert_package_versions() ensures setuptools version is correct
* Some imports changed in pkcli/test.py so that unknown options in pykern test invocations throws correct error
=> Fix #161: pksetup assert versions

pykern/pksetup.py, setup.py
- No, implicitly tested
- none
- None
- Works with python 3.7.2 and 3.10
- No
- No
=> fix #165 setuptools 62.1.0 works

pykern/pkcli/test.py, tests/pkcli/test_test.py
Now you can run `pykern test` in `tests/` without getting `error: no tests found`
See #167
=> Fix #168: recognize if in test dir

pykern/pkunit.py, tests/pkunit1_data/curly_brackets.in/sample.txt, tests/pkunit1_data/curly_brackets.out/sample.txt, tests/pkunit1_test.py
- @gurhar1133 please write a deviance test that forces the pkfail message to include `{something}`, e.g. two files one with `{something}` and one with `{not something}`.
- none
- none
- yes
- no
- no
=> 20220916 Fix #274 use format strings with pkfail

pykern/pkcli/github.py
In the event the glob matches multiple values. For example, radiasoft-zgoubi.git and radiasoft-zgoubi.github.io.git. Then use the first result which will be the shorter and more "specific" result.
- N
- N
- N
- I hope... hard to test
- N
- N
@robnagler this seems rather challenging to test and I'm concerned about edge cases I'm not thinking of. Any thoughts?
=> Fix #280: removed todo, require ext arg

pykern/package_data/projex/projex/__init__.py.jinja, pykern/package_data/projex/projex/projex_console.py.jinja, pykern/package_data/projex/setup.py.jinja, pykern/package_data/projex/tests/conftest.py.jinja, pykern/package_data/projex/tests/import_test.py.jinja, tests/pkcli/projex_test.py
The 5 classifiers that I kept are the most common across popular projects on PyPi.
New projects with init_tree pass ci. I changed formatting in the jinjas to match the expected output of fmt.
=> fix #185: projex upgrade

pykern/pkcli/ci.py, pykern/pkcli/fmt.py, pykern/pkcli/github.py, pykern/xlsx.py, setup.py, tests/pkcli/fmt_data/check1.out/pkexcept
The problem I mentioned in today's meeting was in fact [a bug that was fixed](https://github.com/psf/black/issues/2598) in version 22.12.0, and we only required >=22.0 (I was running 22.6.0.)
This update is enforcing new requirements, hence the change to pykern/pkcli/github.py and pykern/xlsx.py.
rshellweg passes ci format checks on my machine with these changes, but running `pykern fmt run .` will change files that `pykern ci run` does not diff. (Running `pykern fmt run .` in rshellweg will format those example files that were failing `pykern ci run`). Do we want `pykern fmt run .` to only run on `<pkg>`, `tests`, `setup.py `when run from the repo root?
=> fix #329: fmt.diff checks same paths as ci._check_files

pykern/pkunit.py
_update_message is shared for ndiff and regular diff failures for when we want to cp actual to expect
=> Fix #333: cp prompt for ndiff

pykern/pkunit.py
`self._update_message` is set earlier in `self._set_expect_and_actual()`
sirepo example works now. Tests pass on pykern and sirepo with this change
=> Fix #357: set update message before early return

pykern/pkcli/github.py
In addition, read gc.log which may have been produced by previous invocations of `git remote update --prune`. --prune runs `git gc` under the covers. Removing the file is needed so the following `git remote update --prune` doesn't produce a warning about the existence of gc.log.
=> Fix #368: add --prune to fix broken refs

pykern/pkasyncio.py
In development it is better to bind to the wildcard ip because it is hard to know the network configuration in advance. So, better to listen on all possible interfaces. In environments where this could be problematic the ip will be configured.
=> Fix #372: bind to wildcard ip address

setup.py
urllib3 version 2.0 and above only supports openssl > 1.1.1. Centos7 comes with openssl version 1.0.2 so we need to pin urllib3 to a version that works with that openssl version.
=> Fix #381: pin urllib to a version that works on centos7

pykern/pkdebug.py, tests/pkcli/projex_test.py, tests/pkdebug2_test.py
I removed the running of python setup.py in projex_test.py. It is not something we use, and it was failing weirdly. We need something else which #62 and #37 address.
=> Fix #387 pkdebug fmt spec

pykern/pkcollections.py, tests/pkjson_test.py
- Sets stronger limit (64 chars) than Python's parse_int (4300 chars)
=> Fix #406 added parse_int to pkjson.load_any

pykern/pkcli/github.py, tests/pkcli/github_test.py
@e-carlin my guess is we don't want to use the biviosoftware repos I've added since they aren't test repos (wiki could change). Any suggestions for non-radiasoft test repos?
Also I added underscore to suggested regex from issue since also allowable for github usernames.
=> Fix #415 change regex to include any user + added to test case

pykern/pkasyncio.py
Tested with simple script running a pkasyncio loop, seems to disable the undesired message.
=> Fix #310 changed debug default in cfg to 'False'

pykern/pkdebug.py, pykern/pkinspect.py, pykern/pkio.py, pykern/pkunit.py, tests/pkasyncio_test.py, tests/pkinspect_test.py
- pkdexc accepts exc_info arg
- Add FileNotFound to exception_is_not_found
- add pkinspect.caller_func_name
- added pkunit.unbound_localhost_tcp_port and LOCALHOST_IP
=> Fix #434 support for radiasoft/sirepo#6636

pykern/pkcli/test.py, pykern/pkconst.py, pykern/pkresource.py, pykern/pksetup.py
- Added PYKERN_PKCLI_TEST_IGNORE_WARNINGS=1 to avoid deprecation warnings on tests. These are normally suppressed, but pytest enables all warnings.
=> Partial #462 remove pkg_resources from pksetup

pykern/pkcli/ci.py
After the last Black upgrade I received feedback that some scientists were confused about why their tests were failing. ci just prints a diff without any context and fails. I think this message would be helpful. Though, maybe it should only print when there is a diff?
=> fix #460: improve error message for fmt diff in ci

pykern/http.py, pykern/pkasyncio.py, pykern/pkdebug.py, pyproject.toml
- Saw a case where the connection was there, but the socket was not so getpeername was not found on logging. Fix #512 Add pkdebug.pkdppretty
Fix #514 Add packages.find.include so other dirs get ignored
=> Fix #513 pkasyncio protect getpeername better

pykern/http.py
By keeping a reference to AsyncHTTPClient in self._client it causes sockets opened by the client to never be freed. Eventually, we run out of file descriptors. Writing the code this way w/o self._client prevents that from happening. This is a stop gap until we can fix the underlying bug.
=> Fix #529: Don't keep reference to tornado.httpclient.AsyncHTTPClient

pykern/pkcli/test.py, pykern/pkconfig.py, test.sh, tests/pkcli/test1_test.py, tests/pkcli/test3_data/tests/0slow_test.py, tests/pkcli/test3_data/tests/1fail_test.py, tests/pkcli/test3_data/tests/2pass_test.py, tests/pkcli/test3_test.py, tests/pkconfig1_test.py
- Also can configure PYKERN_PKCLI_TEST_MAX_PROCS=n
- Speed up with 10 cores is linear from max_procs1 to 4; 8 didn't seem much improvement
- Add pkconfig.parse_positive_int
=> Fix #335 parallelize pkcli.test max_procs=n

pykern/package_data/projex/projex/__init__.py.jinja, pykern/pkcli/github.py, pykern/pkcli/projex.py, pykern/pkcli/rsmanifest.py, pykern/pkcli/sim.py, pykern/pkcli/test.py, pykern/pkcompat.py, pykern/pkdebug.py, pykern/pkresource.py, pykern/pksetup.py, pykern/sql_db.py, tests/pkcli/github_test.py, tests/pkcli/projex1_test.py, tests/pkcli/projex2_data/private.in/private/__init__.py, tests/pkcli/projex2_data/xyzzy1.in/xyzzy1/__init__.py, tests/pkcli/rsmanifest_test.py, tests/pkresource_test.py
- Fix #462 Replace pkg_resources with importlib.resources
=> Fix #571 support py 3.12

pykern/pkasyncio.py
Fixes https://github.com/radiasoft/pykern/issues/605 by adding an exception handling function to ActionLoop.
=> 605 ActionLoop Exception
