- pykern/pkexample.py
> Reverted unary not (see PEP8)

- README.rst
Really just to demonstrate forking and pull requests.
> fixed formatting

- pykern/pkconfig.py
@moellep please use this in your environment and then merge. Thanks
> Fix #50 pkconfig uses PKDict

- pykern/pkcli/github.py
see also https://github.com/radiasoft/devops/issues/230
> Fix #101 issue_update_alpha_pending iterates issues

- pykern/pkunit.py
- tests/pkunit_test.py
Tested against 'string', b'string', and u'string'
> Fix #106 - pkre apply pkcompat to actual

- pykern/pkio.py
- Don't need to create a list or py_path in not file_re case
> Fix #125 further simplify

- setup.py
see https://github.com/pypa/setuptools/issues/2687
> Fix #117 setuptools must be less than 57

- pull_request_template.md
There are many options for this, but I think it's best to not have hidden files, and put this at the top level.
> Fix #146 added pull_request_template.md at top level

- pykern/pkrunpy.py
- exists
-  no
- no change in use
- no
- no
> Fix #65 convert to use importlib

- pull_request_template.md
- doc only
- no
- no
- yes and done
- added check
> Fix #153 added backwards compatible

- pykern/pkunit.py
- setup.py
- No
- No
- Yes
- Yes
- No
- No
> 182 openpyxl

- pykern/xlsx.py
- no
- no
- n/a
- n/a
- n/a
- n/a
> remove debug print

- pykern/pksetup.py
- tests/pkcli1_test.py
- N/A
- N/A
- N/A
- Yes
- No
- No
> fix #212 qualify pksetup imports

- pykern/pkio.py
- tests/pkio_test.py
- Yes
- None
- No, probably should be
- Yes
- n/a
- n/a
> Fix #205 wrap read/write_text in try with raise from

- pykern/pkcli/ci.py
- tests/pkcli/ci_data/check_prints1.in/x.py
- tests/pkcli/ci_data/check_prints1.out/pkexcept
- tests/pkcli/ci_data/check_prints2.in/x.py
- yes
- no
- n/a
- yes
- yes
- no
> Fix #235 check_prints more flexible and improved doc

- pykern/fconf.py
- pykern/pkcollections.py
Fixes from https://github.com/radiasoft/pykern/pull/231
- no
- no
- n/a
- yes
- no
- no
> fix #238 review comments

- pykern/pkcli/ci.py
- tests/pkcli/ci_data/check_prints1.in/run/ignored.py
- yes
- no
- no
- no, but ok
- no
- no
> fix #241 ignore top level run dir in ci.run

- pykern/pkcli/github.py
- tests/pkcli/github_test.py
- yes
- n/a
- n/a
- yes
- yes
- no
> Fix #264 github.backup hard links to save space

- pykern/pkasyncio.py
Companion for radiasoft/raydata#22
- N
- N
- N/A
- Y
- Y
- N
> First pass at creating abstractions around tornado/asyncio

- pykern/pkcli/ci.py
- pykern/pkcli/fmt.py
Not sure if needs a test. Happy to write one if you want @robnagler
> 221 ci fmt fail no files

- pykern/quest.py
- no, it's a skeleton module
- n/a
- n/a
- yes
- n/a
- n/a
> Fix #205 pykern.quest basic module

- pykern/pkcli/test.py
- tests/pkcli/test_test.py
- added
- n/a
- please do
- yes
- done
- no
> Fix #287 added skip_past to pkcli.test

- pykern/pkcli/github_orgmode.py
- tests/pkcli/github_orgmode_data/assignee_issues-1.out/assignee_issues.org
- tests/pkcli/github_orgmode_data/from_issues-1.out/radiasoft-test-pykern-github-orgmode.org
- tests/pkcli/github_orgmode_test.py
Aslo added created_at as property. Misc bugs.
> 20221014 Fix #302 githhub_org.from_issues multiple repos

- pykern/pkasyncio.py
- pykern/pkcli/github.py
- pykern/pkconfig.py
- tests/pkconfig4_test.py
- tests/pkconfig5_test.py
- tests/pkconfig6_test.py
- tests/pkconfig7_test.py
- fixed some pkconfig tests to use pkunit
> Fix #359 add and use pkconfig.in_dev_mode

- pykern/pkcollections.py
- tests/pkcollections_test.py
This is needed for rsconf/rsaccounting
> Fix #379 added PKDict.pknested_set

- pykern/pkcli/github.py
- tests/pkcli/github_test.py
Added check and test to ensure not backing empty wiki repos. Test backs up once then checks whether there is/isn't a 'config' file in repo backup.
> Fix #367 missing wiki errors

- pykern/xlsx.py
I may add to this PR so don't merge right away.
> Fix #390 better error msg for too many operands

- pykern/util.py
- pykern/x/x.py
See [related sirepo PR](https://github.com/radiasoft/sirepo/pull/6453)
> Fix #405: init db dir

- setup.py
Temporary fix to get around new breaking changes
https://argh.readthedocs.io/en/latest/changes.html#version-0-30-0-2023-10-21
> Fix #413: pin argh

- pykern/pkcli/github.py
- tests/pkcli/github_test.py
- Added `--include-forks` to github.list_repos
> Fix #419 github.backup requires org param

- pykern/pkcli/github.py
Addressing some issues mentioned in this [PR](https://github.com/radiasoft/pykern/pull/420)
> Fix #421 removed temp var + replaced _TEST_REPO with PKDict list

- pykern/pkcli/github.py
- pykern/pkjson.py
- pykern/pkunit.py
- tests/pkcli/github_test.py
- Fix github_test to use new structure of github._TEST_REPOS
> Fix #430 add pkjson.dump_str and log pkunit case_dir

- pykern/http.py
- pykern/pkasyncio.py
- pykern/quest.py
Fix #517 http log includes req_id and log entries
Fix #516 Add pykern.quest.APIError
> Fix #518 http server/client encodes datetime as int

- .gitignore
- pykern/package_data/projex/dot-gitignore.jinja
- pykern/pkcli/sphinx.py
> Fix #522 add --module-first to sphinx.prepare

- pykern/api/client.py
- Subscribe calls may not be found so ok in read_loop
> Fix #559 added missing braces

- pykern/api/server.py
- rename pykern_ attrs to pykern_api_ for consistency
> Fix #563 api.server accepts http_config.uri_map
